### ISSUE TITLE
MaterialManager selection similar to "highlightByID"

### ISSUE THREAD

**Issue by MadsHolten** [ThatOpen/engine_components#226] opened 2023-12-20 18:14 UTC
### Description 📝

The fragment highlighter has a highlightByID method that takes a FragmentIdMap and highlights specific elements in each fragment. It would be great to also have this functionality in the MaterialManager.

### Suggested solution 💡

Imlement a applyByID method in the MaterialManager.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by MadsHolten** [comment] 2024-01-17 17:53
Hi @HoyosJuan  :)

I have been working with fragments for a while, so I'm aware of the setup with merged fragments. For example all walls at one level. As long as I don't need to color specific elements in this group I can do an implementation that just switches the material of the whole block. But I am happy to hear that you are looking into a solution that lets us manipulate the individual elements in the block!

I will stay tuned!

**Comment by agviegas** [comment] 2024-06-20 20:05
Hey @MadsHolten we did a huge improvement of the library. Now fragments allow colorization natively, so you can colorize them using the classifier (check out [this tutorial](https://docs.thatopen.com/Tutorials/Components/Core/Classifier)). From now on, this is the intended way to apply colors to fragments with our library, and it supports any filters of the classifier. Does this solve this issue?

**Comment by agviegas** [comment] 2024-07-02 12:22
@MadsHolten closing this for now. If the issue is not solved, let us know!

**Closed by agviegas** 2024-07-02 12:22 UTC
Labels: feature
