### ISSUE TITLE
Dimension marker not removed after measurement disabled

### ISSUE THREAD

**Issue by MadsHolten** [ThatOpen/engine_components#433] opened 2024-07-02 16:44 UTC
### Describe the bug 📝

The little maker for LengthMeasurement, AreaMeasurement and AngleMeasurement is still shown in the dom after the tool has been disabled. This is still the case after the deleteAll and cancelCreation methods are executed.

The image below shows a scene where I have done a few measurements and disabled the measure tool + deleted all dimensions after each use (on esc key press event). The result is a whole little collection of red markers.

![image](https://github.com/ThatOpen/engine_web-ifc/assets/13613073/ca2b1d9b-6efe-4494-85fd-078fe82d84fc)

### System Info 💻

```shell
MacBook Pro M3
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment] 2024-07-02 19:46
Duplicate of #415. I'll get to this now, and I'll answer there. Closing this!

**Closed by agviegas** 2024-07-02 19:46 UTC
Labels: bug
