### ISSUE TITLE
Improve culler behavior

### ISSUE THREAD

**Issue by shahbaziparisa** [ThatOpen/engine_components#427] opened 2024-07-01 04:59 UTC
### Describe the bug 📝

Hi
In previous versions, before new documentation, I could load large files of 200 MB, and worked correctly. But now the same files don't work smoothly. My browser is hanging.
Rotating the model takes a long time.
I asked other developers too, they have the same problem.
My customer told me after fixing this bug we would pay for the project I had spent 2 months on.

This is one of ifc files:
https://drive.google.com/file/d/12u25nWaniEVxg4jh85_Gm8yzLoyM3Njr/view?usp=sharing

look at speed in this video:

https://github.com/ThatOpen/engine_components/assets/70272544/daf20ec1-f653-4566-acff-01057397666a

### Steps to reproduce 🔢

I use npm start
React.js app

### System Info 💻

```shell
Macbook pro m2
```

### Used Package Manager 📦

npm
  "@thatopen/components": "^2.0.20",
    "@thatopen/components-front": "^2.0.19",
    "@thatopen/fragments": "^2.0.7",
    "@thatopen/ui": "^2.0.8",
    "@thatopen/ui-obc": "^2.0.12",

### Error Trace/Logs 📃

.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment] 2024-07-01 08:51
The reason you are experiencing performance issues is that you are not using the [culler](https://docs.thatopen.com/Tutorials/Components/Core/Cullers). As explained in the docs, the culler is needed to improve the performance of bigger scenes.

When I load the IFC without using the culler, it looks like in your video:

https://github.com/ThatOpen/engine_components/assets/56475338/f98f01d8-0c7d-4797-a228-a62912c4705f

I just used exactly the same code as in the [IfcLoader](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader) tutorial, but changed the loading function to add the loaded fragments to the culler:

```ts
const cullers = components.get(OBC.Cullers);
const culler = cullers.create(world);
culler.threshold = 10;

async function loadIfc() {
  const file = await fetch(
    "../../../../../resources/parisa.ifc",
  );
  const data = await file.arrayBuffer();
  const buffer = new Uint8Array(data);
  const model = await fragmentIfcLoader.load(buffer);
  model.name = "example";
  world.scene.three.add(model);

  for (const child of model.children) {
    if (child instanceof THREE.InstancedMesh) {
      culler.add(child);
    }
  }

  culler.needsUpdate = true;

  world.camera.controls.addEventListener("sleep", () => {
    culler.needsUpdate = true;
  });
}
```

This is the result:

https://github.com/ThatOpen/engine_components/assets/56475338/f4521ef4-2d3f-492e-8816-eeaf823998de

**Comment by shahbaziparisa** [comment] 2024-07-02 07:35
> The reason you are experiencing performance issues is that you are not using the [culler](https://docs.thatopen.com/Tutorials/Components/Core/Cullers). As explained in the docs, the culler is needed to improve the performance of bigger scenes.
> 
> When I load the IFC without using the culler, it looks like in your video:
> 
>  2024-07-01.10-49-40.mp4 
> I just used exactly the same code as in the [IfcLoader](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader) tutorial, but changed the loading function to add the loaded fragments to the culler:
> 
> ```ts
> const cullers = components.get(OBC.Cullers);
> const culler = cullers.create(world);
> culler.threshold = 10;
> 
> async function loadIfc() {
>   const file = await fetch(
>     "../../../../../resources/parisa.ifc",
>   );
>   const data = await file.arrayBuffer();
>   const buffer = new Uint8Array(data);
>   const model = await fragmentIfcLoader.load(buffer);
>   model.name = "example";
>   world.scene.three.add(model);
> 
>   for (const child of model.children) {
>     if (child instanceof THREE.InstancedMesh) {
>       culler.add(child);
>     }
>   }
> 
>   culler.needsUpdate = true;
> 
>   world.camera.controls.addEventListener("sleep", () => {
>     culler.needsUpdate = true;
>   });
> }
> ```
> 
> This is the result:
> 
>  2024-07-01.10-41-02.mp4



> The reason you are experiencing performance issues is that you are not using the [culler](https://docs.thatopen.com/Tutorials/Components/Core/Cullers). As explained in the docs, the culler is needed to improve the performance of bigger scenes.
> 
> When I load the IFC without using the culler, it looks like in your video:
> 
>  2024-07-01.10-49-40.mp4 
> I just used exactly the same code as in the [IfcLoader](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader) tutorial, but changed the loading function to add the loaded fragments to the culler:
> 
> ```ts
> const cullers = components.get(OBC.Cullers);
> const culler = cullers.create(world);
> culler.threshold = 10;
> 
> async function loadIfc() {
>   const file = await fetch(
>     "../../../../../resources/parisa.ifc",
>   );
>   const data = await file.arrayBuffer();
>   const buffer = new Uint8Array(data);
>   const model = await fragmentIfcLoader.load(buffer);
>   model.name = "example";
>   world.scene.three.add(model);
> 
>   for (const child of model.children) {
>     if (child instanceof THREE.InstancedMesh) {
>       culler.add(child);
>     }
>   }
> 
>   culler.needsUpdate = true;
> 
>   world.camera.controls.addEventListener("sleep", () => {
>     culler.needsUpdate = true;
>   });
> }
> ```
> 
> This is the result:
> 
>  2024-07-01.10-41-02.mp4

Please check this model
https://solidcloud.parisashahbazi.com/orange.ifc

load parts with your code by culler takes a lot of time.
I need sth like in the first part of the video like: https://3dviewer.net/.
Is it possible to make it faster for good appearance by culling?


https://github.com/ThatOpen/engine_components/assets/70272544/4f7ccaca-8d74-4dcc-ac90-6e9abd5046fd

**Comment by agviegas** [comment] 2024-07-02 07:49
@shahbaziparisa I can take a look to improve it. That said, keep in mind that we are a small team and we won't be able to take a look at it until the end of the week. 

I understand your situation at work, but we are making this code for free and we can't go faster. Insisting more in all our networks (LinkedIn, That Open People, etc) won't make us go faster 😅 If you are really in a hurry, you can also look for a solution and contribute with a pull request. I'll get back to you when I have news!

For now, I'm reopening this issue.

**Comment by shahbaziparisa** [comment] 2024-07-02 08:26
> @shahbaziparisa I can take a look to improve it. That said, keep in mind that we are a small team and we won't be able to take a look at it until the end of the week.
> 
> I understand your situation at work, but we are making this code for free and we can't go faster. Insisting more in all our networks (LinkedIn, That Open People, etc) won't make us go faster 😅 If you are really in a hurry, you can also look for a solution and contribute with a pull request. I'll get back to you when I have news!
> 
> For now, I'm reopening this issue.

Thanks a million.
Sorry for my questions

**Comment by shahbaziparisa** [comment] 2024-07-29 08:31
> @shahbaziparisa I can take a look to improve it. That said, keep in mind that we are a small team and we won't be able to take a look at it until the end of the week.
> 
> I understand your situation at work, but we are making this code for free and we can't go faster. Insisting more in all our networks (LinkedIn, That Open People, etc) won't make us go faster 😅 If you are really in a hurry, you can also look for a solution and contribute with a pull request. I'll get back to you when I have news!
> 
> For now, I'm reopening this issue.

Hi
unfortunately after a month I could not solve performance problem for my client.When I use latest version I have to use tiles and culling When I use it all details did not appear .
If I have to use first version like openbim 1.3.2 tell me please for high performance.

my model is this :
https://drive.google.com/file/d/1CVEMAn-6sepB7K4VRkwM-pH1UrB38We0/view?usp=sharing

result should be like this:
![Screenshot 2024-07-27 at 7 36 42 PM](https://github.com/user-attachments/assets/7257a440-e5d3-48b0-a1f9-8f275bf6e914)

but with latest version 2.1.14 and using culker result is this:


https://github.com/user-attachments/assets/4139ce39-882f-4431-a496-7b87ef8d2f4f


what is different with this template?
https://thatopen.github.io/engine_web-ifc/demo/

**Comment by agviegas** [comment] 2024-07-29 09:18
Hi! As said above, we'll take a look at this asap. This is a free and open source project, so you are also free to address the issue yourself and propose a solution. Otherwise, we'll take a look when we can, hopefully soon.

**Comment by shahbaziparisa** [comment] 2024-07-29 11:12
> Hi! As said above, we'll take a look at this asap. This is a free and open source project, so you are also free to address the issue yourself and propose a solution. Otherwise, we'll take a look when we can, hopefully soon.
Thanks.
So I have to use old versions for large files yes?

**Comment by agviegas** [comment] 2024-07-29 12:14
You can use whatever fits your needs. We'll fix performance in the modern version as soon as we can

**Comment by shahbaziparisa** [comment] 2024-07-30 20:33
> You can use whatever fits your needs. We'll fix performance in the modern version as soon as we can

Can we use the latest version and the old version on the same project?

**Comment by agviegas** [comment] 2024-08-02 09:18
I don't know if that's possible, the library is not designed to do that. Nevertheless, I'll try to address this issue today, so maybe you want to wait until I check this out to see if you can use the latest version directly

**Comment by agviegas** [comment] 2024-08-04 16:01
Hi @shahbaziparisa I've been checking out this IFC and the problem is that **each brick** is a different geometry. The result is that when I only load the walls, I get 86,000 meshes, which result in 86,000 draw calls.

![image](https://github.com/user-attachments/assets/38cbd9df-b712-428a-8e47-ec5c55ef7db5)

Our library deduplicates geometry according to the IFC. This IFC doesn't have any deduplication, so we just represent what we find. The reason this IFC is visible in other viewers is because they merge the geometry in a single buffergeometry, which in this specific case is favourable.

This is not a problem of the culler, but a problem of the IFC itself. I think this problem has 2 possible solutions:

1. Create your own loader using [our core library](https://github.com/ThatOpen/engine_web-ifc) using a merging strategy rather than an instancing strategy like we do. This might be a lot of work, and most tools of our library (like highlighting) won't work with it, so I don't recommend you to do this.

2. Create a deduplication algorithm and apply it to the IFC to this IFC to optimize it before loading it in the viewer. This is something we might want to implement in the library ourselves, so we could maybe implement it and add it to the library, so you can just use it.

I think 2 is the best way to go. I'm closing this issue for now, feel free to create a new issue requesting a deduplication feature and we can take care. Cheers!

**Closed by agviegas** 2024-08-04 16:01 UTC
Labels: feature
