### ISSUE TITLE
[Bug]: IFC files with spatial reference systems (and/or georeferenced)

### ISSUE THREAD

**Issue by onderilkesever** [ThatOpen/engine_components#495] opened 2024-09-04 07:55 UTC
### What happened?

Hi, 
I am using the library to convert an IFC file which has a spatial reference system & georeferenced to fragments group. The resulting fragments group seems to be appearing at the correct place but with the wrong orientation. But I cannot find any documentation regarding this support. So I wonder, is this a bug that supposed to be working? Can you please share what is coming from the library and what is not so that we can understand what we should be doing to support IFC files with spatial reference systems and/or georeferenced? 
Thanks

### Version

0.0.56

### What browsers are you seeing the problem on?

Chrome

**Comment by onderilkesever** [comment] 2024-09-26 13:41
Hi @agviegas & @beachtom, 
I created one small reproducible example that hopefully will help us. Here is the small project -> https://drive.google.com/file/d/1A6CWnooy9Yp_eVC9H3nNO_V8UU75umT6/view?usp=sharing
The imports you see on the file are referring two files that I already shared above 
```
import ifcPath from './assets/HQ.ifc';
import ifcPath2 from './assets/HQ_georeferenced.ifc';
```
Georef -> https://drive.google.com/file/d/1R-mR17RH20AJ-2E6djFOUUxg9THLSPui/view?usp=drive_link
Without georef -> https://drive.google.com/file/d/13QEY3arAjrYe49Wfp5P6uGv5nQrIstlM/view?usp=sharing

Those two files are basically the same, but their only difference is georeferencing information(IfcProjectedCrs & IfcProjectedCrs). 

Try loading one or another by commenting out either lines 50 OR 51. You will realise one of the models will not appear on scene origin. Can you please help me understand which library is causing this difference and how? 
I am looking forward to hearing back. 
Thanks!

**Comment by agviegas** [comment] 2024-10-23 11:14
Hey @onderilkesever I think we alredy discussed this [here](https://github.com/ThatOpen/engine_components/issues/493). By default, web-ifc (our core IFC library) positions the model according to the [IFC spatial structure](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcproductextension/lexical/ifcspatialstructureelement.htm). When using `COORDINATE_TO_ORIGIN`, the library takes the first vertex of the first geometry that it finds and brings it to the origin (0, 0, 0) to prevent nummerical stability issues. This generates a `coordinationMatrix` that you can use to align multiple models together. Of course, if `COORDINATE_TO_ORIGIN=false`, then models that were aligned in the authoring app and correctly exported should be aligned automatically.

As for this specific case, I believe the cause behind the difference in the rotation is the orientation of the `IFCGEOMETRICREPRESENTATIONCONTEXT`, which you can see in the screenshot below.

![image](https://github.com/user-attachments/assets/a16e8f29-efa7-4bad-93a6-bb86b0088222)

Closing this as I believe the library is working as expected, but feel free to ping me and I'll be happy to solve any remaining questions/doubts.

**Closed by agviegas** 2024-10-23 11:14 UTC
Labels: bug
