### ISSUE TITLE
IfcPropertiesFinder in node server

### ISSUE THREAD

**Issue by Sulaiman2018** [ThatOpen/engine_components#309] opened 2024-02-29 15:57 UTC
### Describe the bug 📝

Apologies, it's not a bug.

I want to ask if this library can be used directly on a Node server without making any changes, and if the IfcPropertiesFinder component can be used from Node.js. Our goal is to make queries about data related to IFC classes, we do not require any graphical functionalities.

Thank you very much for your help and consideration. Looking forward to your response. 

### Steps to reproduce 🔢

No steps

### System Info 💻

```shell
No system Info.
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment] 2024-04-11 19:14
Hi @Sulaiman2018! Thanks a lot for get in touch.

The quick answer for question is no, you can't use the component in a node server without any modifications. However, we hope in the next release (1.6.0) than happens to be in mid-May, to be able to run many components in the server as we are going to separate the core logic to the graphics logic. Let's hope the time is enough!

For any type of inquiries that are not bugs or feature requests, you can use our free community at www.people.thatopen.com, particularly the space named "Ask the community" 🙂

As this is not a bug, I will close it now. But feel free to ask any questions in the community! We will be more than happy to answer you.

Thanks a lot!

**Closed** 2024-04-11 19:14 UTC
Labels: bug
